# Generated by Django 2.1 on 2018-12-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20181217_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='requests_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
