# Generated by Django 2.1 on 2019-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organization_requests_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_expire_days',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
