# Generated by Django 2.1 on 2019-03-08 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_organization_billing_expire_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='billing_expire_days',
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
