# Generated by Django 2.1 on 2019-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_auto_20190308_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='billing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
