# Generated by Django 2.1 on 2018-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhook',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='eventhook',
            name='urls',
        ),
        migrations.AddField(
            model_name='eventhook',
            name='hook_link',
            field=models.CharField(choices=[('url', 'url'), ('email', 'email')], default='url', max_length=500),
        ),
    ]
