# Generated by Django 2.1 on 2018-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181220_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhook',
            name='hook_type',
            field=models.CharField(choices=[('url', 'url'), ('email', 'email')], default='url', max_length=6),
        ),
        migrations.AlterField(
            model_name='eventhook',
            name='hook_link',
            field=models.CharField(max_length=500),
        ),
    ]
