# Generated by Django 2.1 on 2018-12-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organization_requests_no'),
        ('events', '0003_auto_20181220_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhook',
            name='org',
        ),
        migrations.AddField(
            model_name='eventhook',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='orgs.Organization'),
        ),
    ]
