# Generated by Django 2.1 on 2019-01-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventhook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
