# Generated by Django 2.1 on 2019-02-13 11:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhook',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
