# Generated by Django 2.1 on 2019-04-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventhook_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventService'),
        ),
    ]
