# Generated by Django 2.1 on 2018-12-11 13:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=191)),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=250, unique=True)),
                ('balance_transaction', models.CharField(blank=True, max_length=250)),
                ('order_id', models.CharField(max_length=250, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('full_response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
