# Generated by Django 2.1 on 2018-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20181211_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_message',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
