# Generated by Django 2.1 on 2018-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20181212_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
