# Generated by Django 2.1 on 2018-12-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20181210_0936'),
        ('billing', '0004_auto_20181212_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='org',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Organization'),
        ),
    ]
